sudo: required

language: node_js
node_js:
  - 12

services:
  - docker

# before_script:
#     echo 'placeholder'

cache: npm

script:
    npm ci && npm test

# after_success:
#   - if [ "$TRAVIS_BRANCH" == "master" ]; then
#     docker build -t sauliuz/boardjs:v0.1."$TRAVIS_BUILD_NUMBER" . ;
#     docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
#     docker push sauliuz/boardjs:v0.1."$TRAVIS_BUILD_NUMBER";
#     fi